// <auto-generated />
namespace eProiect.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class classesConfirm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(classesConfirm));
        
        string IMigrationMetadata.Id
        {
            get { return "202405162112333_classesConfirm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
