// <auto-generated />
namespace eProiect.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _202404081116514_initialState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202404081116514_initialState));
        
        string IMigrationMetadata.Id
        {
            get { return "202404081132441_202404081116514_initialState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
