// <auto-generated />
namespace eProiect.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PreAlphaModel11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PreAlphaModel11));
        
        string IMigrationMetadata.Id
        {
            get { return "202403291210039_PreAlphaModel11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
